### ISSUE TITLE
Next: Failing e2e tests in next branch

### ISSUE THREAD

**Issue by jpoehnelt** [googlemaps/js-samples#997]
```
 1) samples/playground.spec.ts:20:5 › suite › playground preview runs without error - deckgl-arclayer 

    Error: CDN HTTP 404 error (https://unpkg.com/gl-matrix@3.3.0/vec3): Cannot find an index in "/vec3" in gl-matrix@3.3.0

        at _e._fetch (http://localhost:8000/playground-typescript-worker.871f8c44.js:41:1048)
        at async _e.canonicalize (http://localhost:8000/playground-typescript-worker.871f8c44.js:41:324)
        at async ee._handleBareSpecifier (http://localhost:8000/playground-typescript-worker.871f8c44.js:31:2110)

  2) samples/playground.spec.ts:20:5 › suite › playground preview runs without error - deckgl-points 

    Error: CDN HTTP 404 error (https://unpkg.com/gl-matrix@3.4.3/vec3): Cannot find an index in "/vec3" in gl-matrix@3.4.3

        at _e._fetch (http://localhost:8000/playground-typescript-worker.871f8c44.js:41:1048)
        at async _e.canonicalize (http://localhost:8000/playground-typescript-worker.871f8c44.js:41:324)
        at async ee._handleBareSpecifier (http://localhost:8000/playground-typescript-worker.871f8c44.js:31:2110)

  3) samples/playground.spec.ts:20:5 › suite › playground preview runs without error - deckgl-tripslayer 

    Error: CDN HTTP 404 error (https://unpkg.com/gl-matrix@3.3.0/vec2): Cannot find an index in "/vec2" in gl-matrix@3.3.0

        at _e._fetch (http://localhost:8000/playground-typescript-worker.871f8c44.js:41:1048)
        at async _e.canonicalize (http://localhost:8000/playground-typescript-worker.871f8c44.js:41:324)
        at async ee._handleBareSpecifier (http://localhost:8000/playground-typescript-worker.871f8c44.js:31:2110)
        at async ee._handleModule (http://localhost:8000/playground-typescript-worker.871f8c44.js:31:984)
        at async ee._fetchExternalDependency (http://localhost:8000/playground-typescript-worker.871f8c44.js:31:2719)
        at async http://localhost:8000/playground-typescript-worker.871f8c44.js:6:447

  4) samples/playground.spec.ts:20:5 › suite › playground preview runs without error - marker-clustering 

    The requested module '../../../../skmeans@0.9.7/dist/node/main.js' does not provide an export named 'default'

  5) samples/playground.spec.ts:20:5 › suite › playground preview runs without error - react-map ===

    Error: Error 404 fetching project config from http://localhost:8000/samples/react-map/playground/playground.ts.json: 

        at We (http://localhost:8000/index.js:101:736)
        at async Ue._loadProjectFromSource (http://localhost:8000/index.js:91:8129)

  Slow test file: samples/playground.spec.ts (8m)
  Consider splitting slow test files to speed up parallel execution

  5 failed
    samples/playground.spec.ts:20:5 › suite › playground preview runs without error - deckgl-arclayer 
    samples/playground.spec.ts:20:5 › suite › playground preview runs without error - deckgl-points 
    samples/playground.spec.ts:20:5 › suite › playground preview runs without error - deckgl-tripslayer 
    samples/playground.spec.ts:20:5 › suite › playground preview runs without error - marker-clustering 
    samples/playground.spec.ts:20:5 › suite › playground preview runs without error - react-map ====
  162 passed (8m)
  ```

**Comment by jpoehnelt** [comment]
`store-locator` hits OVER_QUERY_LIMIT and `programmatic-load-button` needs to be triggered.
